# name: Build and Push Docker Image
# on:
#   push:
#     branches:
#       - master   # runs when pushing to main, adjust if needed
# jobs:
#   docker:
#     runs-on: ['self-hosted', 'pi']
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Cache Gradle packages
#         uses: actions/cache@v3
#         with:
#           path: |
#             ~/.gradle/caches
#             ~/.gradle/wrapper
#           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#           restore-keys: |
#             ${{ runner.os }}-gradle-
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Build and push Docker image
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           platforms: linux/amd64
#           push: true
#           tags: |
#             john4064/doble-pipeline:latest
