name: Code Quality

on: [ pull_request]

jobs:
  quality:
    runs-on: ['self-hosted', 'pi']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run Detekt
        run: ./gradlew detekt
      - name: Run Spotless Check
        run: ./gradlew spotlessCheck